version: '3.8'
services:
    server:
        build: ./server
        expose:
            - ${APP_SERVER_PORT}
        environment: 
                API_HOST: ${API_HOST}
                APP_SERVER_PORT: ${APP_SERVER_PORT}
        ports: 
                - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
        volumes: 
                - ./server:/server
        command: node server.js
    client:
        build: ./client
        expose:
            - ${REACT_APP_PORT}
        environment: 
            REACT_APP_PORT: ${REACT_APP_PORT}
        ports: 
            - 80:${REACT_APP_PORT}
        stdin_open: true
        volumes: 
                - ./client/src:/client/src
                - ./client/public:/client/public
        links:
                - server
        command: npm run start
    